module.exports = {
  "239": {
    "item_id": "239",
    "resolved_id": "239",
    "given_url": "http://www.dooce.com/",
    "given_title": "dooce",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308901",
    "time_updated": "1523244251",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1095,
    "resolved_title": "I'm Heather B. Armstrong. This is my website.",
    "resolved_url": "http://dooce.com/",
    "excerpt": "While we have all been motivated to take on more of an activist role in our daily lives, we also need some intermittent distraction to ease strain on the brain. And oh, the strain on the brain to come.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "1",
    "word_count": "295",
    "lang": ""
  },
  "1292": {
    "item_id": "1292",
    "resolved_id": "1292",
    "given_url": "http://www.digg.com/",
    "given_title": "digg",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308904",
    "time_updated": "1523244251",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1037,
    "resolved_title": "Digg - What the Internet is talking about right now",
    "resolved_url": "http://digg.com",
    "excerpt": "Skip to content, or skip to search.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "1",
    "word_count": "1527",
    "lang": "en",
    "time_to_read": 7,
    "top_image_url": "http://static.digg.com/static/fe/9c69c3/images/logo-og-digg@2x.png"
  },
  "1894": {
    "item_id": "1894",
    "resolved_id": "1894",
    "given_url": "http://www.dailylit.com/",
    "given_title": "DailyLit",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308896",
    "time_updated": "1523244253",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1209,
    "resolved_title": "Welcome to DailyLit",
    "resolved_url": "http://dailylit.com/",
    "excerpt": "Thousands of people are already using DailyLit to read the books they never thought they had time for. We've already delivered more than 50 million installments—that's hundreds of thousands of books!  It's easy to set up.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "1",
    "word_count": "172",
    "lang": ""
  },
  "4810": {
    "item_id": "4810",
    "resolved_id": "4810",
    "given_url": "http://www.fimoculous.com/archive/post-1825.cfm",
    "given_title": "Fimoculous.com - misc - Best Blogs of 2006 that You (Maybe) Aren&amp;#039;t",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308894",
    "time_updated": "1523244252",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1266,
    "resolved_title": "Best Blogs of 2006 that You (Maybe) Aren't Reading",
    "resolved_url": "http://www.fimoculous.com/archive/post-1825.cfm",
    "excerpt": "Every year around this time, I attempt to summarize what's been happening online by publishing my list of the best blogs of the year [2002, 2003, 2004]. But I abruptly stopped last year because the list had become annoyingly redundant.",
    "is_article": "1",
    "is_index": "0",
    "has_video": "0",
    "has_image": "1",
    "word_count": "1834",
    "lang": "en",
    "time_to_read": 8
  },
  "5057": {
    "item_id": "5057",
    "resolved_id": "5057",
    "given_url": "http://wefeelfine.org/",
    "given_title": "We Feel Fine / by Jonathan Harris and Sep Kamvar",
    "favorite": "0",
    "status": "0",
    "time_added": "1166663135",
    "time_updated": "1522820041",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 2062,
    "resolved_title": "We Feel Fine / by Jonathan Harris and Sep Kamvar",
    "resolved_url": "http://wefeelfine.org",
    "excerpt": "",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "0",
    "lang": ""
  },
  "6219": {
    "item_id": "6219",
    "resolved_id": "6219",
    "given_url": "http://www.cssbasics.com/",
    "given_title": "CSS tutorial",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308903",
    "time_updated": "1523244251",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1061,
    "resolved_title": "Browse CSS Basics",
    "resolved_url": "http://www.cssbasics.com/",
    "excerpt": "CSS Basics Everything you ever wanted to know about the basics of CSS  Main navigation       Welcome Content",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "17",
    "lang": "en"
  },
  "7216": {
    "item_id": "7216",
    "resolved_id": "54710398",
    "given_url": "http://www.melissaclifton.com/tutorial-popart.html",
    "given_title": "Pop Art Inspired by Lichtenstein - Online Tutorial at Melissa Clifton page ",
    "favorite": "0",
    "status": "0",
    "time_added": "1162432699",
    "time_updated": "1522820041",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 2077,
    "resolved_title": "Pop Art Inspired by Lichtenstein",
    "resolved_url": "http://www.melissaevans.com/tutorials/pop-art-inspired-by-lichtenstein",
    "excerpt": "Open your picture in photoshop that is going to become pop art and duplicate the layer called “Background”. (Just click the layer called “Background” and drag it to this icon at the bottom of the layer palette to duplicate the layer.)  Rename this new layer “dots”.",
    "is_article": "1",
    "is_index": "0",
    "has_video": "0",
    "has_image": "1",
    "word_count": "801",
    "lang": ""
  },
  "7499": {
    "item_id": "7499",
    "resolved_id": "7499",
    "given_url": "http://www.authenticjobs.com/",
    "given_title": "Authentic Jobs ~ Full-time and freelance job opportunities for designers an",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308886",
    "time_updated": "1523244253",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1487,
    "resolved_title": "Authentic Jobs: Web, Design, Freelance, and Tech Jobs",
    "resolved_url": "https://authenticjobs.com/#location=UK&query=php",
    "excerpt": "Skip to content",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "3",
    "lang": "en"
  },
  "8128": {
    "item_id": "8128",
    "resolved_id": "8128",
    "given_url": "http://freshome.com/2008/02/25/30-of-the-most-creative-bookshelves-designs/",
    "given_title": "Bookshelves - 30 of the Most Creative Designs",
    "favorite": "0",
    "status": "0",
    "time_added": "1523244067",
    "time_updated": "1523244068",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 180,
    "resolved_title": "30 of the Most Creative Bookshelves Designs",
    "resolved_url": "http://freshome.com/2008/02/25/30-of-the-most-creative-bookshelves-designs/",
    "excerpt": "At Freshome, we try to find things to inspire you and make your home a better place to live. You can find all kinds of stories here, such as beautiful pieces of furniture, ideas for decorating your home, architecture news, home gadgets, tips and tricks for improving your home, and much more.",
    "is_article": "1",
    "is_index": "0",
    "has_video": "0",
    "has_image": "1",
    "word_count": "1674",
    "lang": "en",
    "time_to_read": 8,
    "top_image_url": "http://cdn.freshome.com/wp-content/uploads/2008/02/Clipboard01.jpg"
  },
  "10632": {
    "item_id": "10632",
    "resolved_id": "10632",
    "given_url": "http://reddit.com/",
    "given_title": "reddit.com: what's new online",
    "favorite": "0",
    "status": "0",
    "time_added": "1153790746",
    "time_updated": "1522820041",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 2163,
    "resolved_title": "This Subreddit",
    "resolved_url": "https://www.reddit.com/",
    "excerpt": "The best posts on Reddit for you, pulled from the most active communities on Reddit. Check here to see the most shared, upvoted, and commented content on the internet.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "1",
    "has_image": "1",
    "word_count": "167",
    "lang": "en",
    "top_image_url": "https://www.redditstatic.com/icon.png"
  },
  "11428": {
    "item_id": "11428",
    "resolved_id": "11428",
    "given_url": "http://www.perpetualkid.com/",
    "given_title": "Perpetual Kid - Unique Gifts to Entertain Your Inner Child",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308897",
    "time_updated": "1523244253",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1185,
    "resolved_title": "Fun + Unique gifts for the young at heart! Unusual + affordable gift ideas for guys, girls, mom, dad, kids, and pets!",
    "resolved_url": "https://www.perpetualkid.com/",
    "excerpt": "At Perpetual Kid, we’ve been dedicated to finding the most fun and unique gifts for over 10 years! Browse our unusual selection of fun and uncommon gifts and gadgets for your own amusement, or to find a lucky gift recipient the perfect present.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "137",
    "lang": "en"
  },
  "13488": {
    "item_id": "13488",
    "resolved_id": "13488",
    "given_url": "http://www.overheardinnewyork.com/",
    "given_title": "Overheard in New York | The Voice of the City",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308901",
    "time_updated": "1523244252",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1090,
    "resolved_title": "Overheard In New York",
    "resolved_url": "http://www.overheardinnewyork.com/",
    "excerpt": "Woman in leggings: What the fuck is this shit? You gonna hand me three motherfucking sugar packets? Do you have any idea how big this coffee is? Cashier: We don’t put sugar in your coffee. Sugar packets are on the counter. Woman in leggings: Listen, my boyfriend’s a cop.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "1",
    "word_count": "642",
    "lang": ""
  },
  "13808": {
    "item_id": "13808",
    "resolved_id": "13808",
    "given_url": "http://www.readatwork.com/",
    "given_title": "Read at Work",
    "favorite": "0",
    "status": "0",
    "time_added": "1523244067",
    "time_updated": "1523244068",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 194,
    "resolved_title": "Readatwork.com",
    "resolved_url": "http://readatwork.com/",
    "excerpt": "",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "0",
    "lang": ""
  },
  "14573": {
    "item_id": "14573",
    "resolved_id": "540078361",
    "given_url": "http://www.tadalist.com/",
    "given_title": "Ta-da List: Simple sharable to-do lists. To-do list, todo list, task manage",
    "favorite": "0",
    "status": "0",
    "time_added": "1106382487",
    "time_updated": "1522820041",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 2292,
    "resolved_title": "A note about Ta-da List",
    "resolved_url": "http://basecamp.com/tadalist-retired",
    "excerpt": "We launched Ta-da List back in January of 2005 so everyone could have a fast and free to-do list app in their web browser. There wasn’t much out there that was good in 2005.  My, how things have changed.",
    "is_article": "1",
    "is_index": "1",
    "has_video": "0",
    "has_image": "1",
    "word_count": "152",
    "lang": ""
  },
  "14804": {
    "item_id": "14804",
    "resolved_id": "14804",
    "given_url": "http://xkcd.com/",
    "given_title": "xkcd - A webcomic of romance, sarcasm, math, and language - By Randall Munr",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308894",
    "time_updated": "1523244252",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1267,
    "resolved_title": "Violin Plots",
    "resolved_url": "https://xkcd.com/",
    "excerpt": "",
    "is_article": "0",
    "is_index": "0",
    "has_video": "0",
    "has_image": "2",
    "word_count": "0",
    "lang": "en"
  },
  "14917": {
    "item_id": "14917",
    "resolved_id": "14917",
    "given_url": "http://lib.ru/NABOKOW/",
    "given_title": "Lib.Ru: Владимир Набоков",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308909",
    "time_updated": "1523244253",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 931,
    "resolved_title": "Владимир Набоков",
    "resolved_url": "http://lib.ru/NABOKOW/",
    "excerpt": "Lib.",
    "is_article": "1",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "719",
    "lang": ""
  },
  "15757": {
    "item_id": "15757",
    "resolved_id": "1778",
    "given_url": "http://www.shelfari.com/",
    "given_title": "Shelfari",
    "favorite": "0",
    "status": "0",
    "time_added": "1173486662",
    "time_updated": "1522820041",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 2043,
    "resolved_title": "Goodreads Choice Awards: The Best Books 2017",
    "resolved_url": "https://www.goodreads.com/",
    "excerpt": "You’re in the right place. Tell us what titles or genres you’ve enjoyed in the past, and we’ll give you surprisingly insightful recommendations.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "39",
    "lang": "en",
    "top_image_url": "https://s.gr-assets.com/assets/facebook/goodreads_wide-e23f6858b6bf20dcaf8493237a214a0e.png"
  },
  "18029": {
    "item_id": "18029",
    "resolved_id": "1002335739",
    "given_url": "http://www.moo.com/",
    "given_title": "moo | we love to print",
    "favorite": "0",
    "status": "0",
    "time_added": "1158700735",
    "time_updated": "1522820041",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 2094,
    "resolved_title": "Print it out there",
    "resolved_url": "https://www.moo.com/us/",
    "excerpt": "We've sent your promo code to your email address. Use it at checkout to get free shipping on your MOO order  Minimum spend for free shipping is $40.00 - don't worry, it's surprisingly easy to do! The free shipping code will expire in 30 days.",
    "is_article": "1",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "44",
    "lang": "en"
  },
  "22992": {
    "item_id": "22992",
    "resolved_id": "1809111",
    "given_url": "http://www.ifilm.com/",
    "given_title": "IFILM - Movies, Trailers, Music and Viral Videos",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308911",
    "time_updated": "1523244253",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 908,
    "resolved_title": "Screen Junkies",
    "resolved_url": "http://screenjunkies.com",
    "excerpt": "Login  Or Log In With Your Email Check out our FAQs if your question has already been answered.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "0",
    "has_image": "0",
    "word_count": "28",
    "lang": "en"
  },
  "23904": {
    "item_id": "23904",
    "resolved_id": "23904",
    "given_url": "http://obsoleteskills.com/Skills/Skills",
    "given_title": "Obsolete Skills: Skills/Skills",
    "favorite": "0",
    "status": "0",
    "time_added": "1523244067",
    "time_updated": "1523244068",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 164,
    "resolved_title": "Obsolete Skills",
    "resolved_url": "http://obsoleteskills.com/Skills/Skills",
    "excerpt": "It doesn’t just happen to large companies; upgrades are necessary to facilities at all levels. In our case, we used to concentrate on honing in on those skills that people could still possibly use, but hardly anyone does (or cares about) anymore.",
    "is_article": "0",
    "is_index": "1",
    "has_video": "1",
    "has_image": "1",
    "word_count": "223",
    "lang": "en"
  },
  "24156": {
    "item_id": "24156",
    "resolved_id": "24156",
    "given_url": "http://www.stetson.edu/~efriedma/numbers.html",
    "given_title": "What&amp;#039;s Special About This Number?",
    "favorite": "0",
    "status": "0",
    "time_added": "1504308892",
    "time_updated": "1523244253",
    "time_read": "0",
    "time_favorited": "0",
    "sort_id": 1306,
    "resolved_title": "What's Special About This Number?",
    "resolved_url": "http://www.stetson.edu/~efriedma/numbers.html",
    "excerpt": "",
    "is_article": "0",
    "is_index": "0",
    "has_video": "0",
    "has_image": "0",
    "word_count": "0",
    "lang": "en"
  }
}